### ISSUE TITLE
Ch23  Fatel Error

### ISSUE THREAD

**Issue by hcri50** [STYSwiftIn24H/Examples#1]
This is the error that I am getting

main: 2014-12-28 21:27:33 +0000
Optional(https://itunes.apple.com/search?term=beatles&country=us)
nil
fatal error: unexpectedly found nil while unwrapping an Optional value

Now when you go to line #26 we are getting a "nil" for "contentsOfURL"

You can download the File Here
https://www.dropbox.com/s/chybzci97si00oa/Ch23.zip?dl=0

**Comment by STYSwiftIn24H** [comment]
Hi @hcri50, I ran the project you provided but I could not replicate the error. Could you maybe upload a screenshot when it happens? Also, what version of Xcode are you using? I'm using Xcode 6.1.1 at the moment. Thanks! -BJ

**Comment by hcri50** [comment]
Thank you I will tomorrow

**Comment by STYSwiftIn24H** [comment]
Hey @hcri50, just wanted to follow up to see if you were still having the crashing issue. I'd love to help if you still need it. Or let me know if it's ok to close this issue. Thanks!

**Comment by hcri50** [comment]
Thank you
I will report back this afternoon

**Comment by hcri50** [comment]
Hello sir,
I got it to open up now and it says Beatles Songs.
I am now able to continue with the exercise. 
THANK YOU AGAIN FOR CHECKING UP ON ME
love your book and I am looking for your next book
Sincerely 
Devoted Reader
Robert DeSaeger

**Comment by STYSwiftIn24H** [comment]
Great! I'm so glad you got it working and you are liking the book. Thank you for your kind words. If you have a minute, would you be so nice to leave a review where you bought the book to let other readers know your thoughts and experiences? Thank you! -BJ

**Comment by hcri50** [comment]
No problem at all
I will be going through it a second time 
Something's I did not fully grasp but going through a second time will help reinforce some of the early concepts
I will do that on Sunday for the review
I usually get a survey to fill out on Amazon
For it gets triggered when it reaches the end of the book
Looking forward to give you a 5 Star 
Take care
And wish you success with your book
Do you have a forum to where we can post ideals for help? 
Thank you

**Comment by STYSwiftIn24H** [comment]
Great, thank you! This github repository is the best place to raise issues and submit corrections. You can also email STYSwiftIn24H@gmail.com or get me on Twitter at bjmillerltd.
